### ISSUE TITLE
[P0] [Umbrella] End-to-end shared object support

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1866]
Shared objects are fully usable in Move by transaction sent from the wallet.
Dependencies:
- [ ] https://github.com/MystenLabs/sui/issues/1822
- [ ] https://github.com/MystenLabs/sui/issues/1790
- [ ] Add comprehensive testing that use shared objects

**Comment by asonnino** [comment]
Done
