### ISSUE TITLE
Narwhal reconfiguration checklist

### ISSUE THREAD

**Issue by andll** [MystenLabs/sui#5829]
This is a shortlist of things we think needs to be done before we can claim that narwhal reconfiguration works

- [ ] Cleanup narwhal tables on reconfiguration
- [ ] (probably) need to just clean-restart all components (except for network)
- [ ] Add epoch to Batch so that they can be cleaned up on reconfiguration, reject batch from incorrect epoch
