### ISSUE TITLE
[Gateway Service] [umbrella] Implement full Gateway Service API

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#615]
This is an umbrella issue that tracks the roadmap of all things we need to do to complete the Gateway Service API, as documented here: https://docs.google.com/document/d/1LYTRODgj5GuufocEqKTqzozJJ7MusFOK_s0f8JKoEaw/edit?usp=sharing
There are 3 main themes of work to be don here:
1. **Architecture**: the components should be abstracted and named properly, only contain information they should contain, and are talking to the necessary components.
2. **API Completeness**: we should have a complete list of API implementation that's comprehensive and accurate to support a variety of applications.
3. **Minimum Authority Read**: we should reduce the amount of read requests to authorities to the minimum, through a combination of local cache, local execution and self-authenticating certificates.

Many of the work can be appealing and we may feel eager to jump in early, but it is important that we work on them with the proper order, to avoid unnecessary refactoring latter on. In general, optimizations should come latter, and architecture work should come in first.

Below is a full list of the work to be done:

- [ ] By GDC:
  - [ ] Architecture
    - [X] Gateway Service API should be implemented at gateway state level, instead of account state level. #577 
    - [x] Rename Client to Gateway. #613
    - [x] Remove private key from Gateway Service. #594 
    - [ ] Make REST API talk to Gateway Service instead of the wallet
    - [ ] Make the wallet talk to the REST API
    - [ ] Cleanups. It is important that we take time to cleanup the code once in a while since a lot of architecture changes lead to code that are out-of-dated.
  - [x] API
    - [x] Change `transfer_object` to `transfer_coin` and improve the response. #612
    - [x] Support raw bytes package in `publish` API. #613
- [ ] After GDC:
  - [ ] Architecture
    - [ ] Redesign gateway service storage (e.g. move per-account Gateway storage to shared storage.) #622
    - [ ] Support full-replica style Gateway Service.
  - [ ] API
    - [ ] Implement all missing APIs described in the design doc
  - [ ] Minimum Authority Read (NOTE: we should finish the Architecture changes first before going after any of this)
    - [ ] Local Transaction Execution
    - [ ] Add Certified Signed Effects that can self-authenticate on a transaction that's already executed by a quorum of authorities
    - [ ] Clearly define the communication semantics of each Gateway API to make sure we are sending minimum read requests to authorities

**Comment by lxfind** [comment]
Most of the things in the list were done. This is largely out of dated now.
